import { Component, input } from "@angular/core";
import { MassTrait } from "../mass-types";

@Component({
    selector: 'rez-mass-trait',
    template: `
        <blockquote>
            @if ((trait().requiredFragments?.length ?? 0) > 0 || (trait().requiredProcessors?.length ?? 0) > 0) {
                <h1>Requirements</h1>
                <rez-mass-element-list [module]="moduleId()" name="Fragments" [elements]="trait().requiredFragments" />
                <rez-mass-element-list [module]="moduleId()" name="Processors" [elements]="trait().requiredProcessors" />
            }

            <h1>Effects</h1>
            <rez-mass-element-list [module]="moduleId()" name="Adds Fragments" [elements]="trait().addsFragments" />
            <rez-mass-element-list [module]="moduleId()" name="Adds Tags" [elements]="trait().addsTags" />
            <rez-mass-element-list [module]="moduleId()" name="Adds Translators" [elements]="trait().addsTranslators" />

            <!-- TODO: this will be autogenerated -->
            <rez-mass-element-list [module]="moduleId()" name="Triggers Processors" [elements]="trait().triggersProcessors" />

            @if (trait().properties?.length ?? 0 > 0) {
                <h1>Properties</h1>
                <rez-mass-property-list [showName]="false" [properties]="trait().properties || []" />
            }
        </blockquote>
    `,
    standalone: false
})
export class MassTraitComponent {
    moduleId = input.required<string>();
    trait = input.required<MassTrait>();
}
